-- 本项目与 danci-admin 共享 Supabase 数据库：
--   - "books" / "words" 表已由 danci-admin 迁移创建（采用既有表为基线，不在此重建）；
--   - "User" 表本由 h5 应用运行时（app/db.ts ensureTableExists）自动创建；此处幂等保障其存在，
--     以确保下方 learning_progress 的外键引用可解析（与运行时创建逻辑兼容）。
-- 本迁移新增 learning_progress 表及其索引，并在既有 words 表补充组合索引。
CREATE TABLE IF NOT EXISTS "User" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(64),
	"password" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "learning_progress" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "learning_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"book_id" text NOT NULL,
	"learned_count" integer DEFAULT 0 NOT NULL,
	"last_word_rank" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "learning_progress" ADD CONSTRAINT "learning_progress_user_id_User_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "learning_progress" ADD CONSTRAINT "learning_progress_book_id_books_bookId_fk" FOREIGN KEY ("book_id") REFERENCES "public"."books"("bookId") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "learning_progress_user_book_unique" ON "learning_progress" USING btree ("user_id","book_id");--> statement-breakpoint
CREATE INDEX "idx_progress_user" ON "learning_progress" USING btree ("user_id","updated_at");--> statement-breakpoint
CREATE INDEX "idx_words_book_rank" ON "words" USING btree ("bookId","wordRank");