CREATE TABLE "user_book_progress" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_book_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"book_id" text NOT NULL,
	"learned_count" integer DEFAULT 0 NOT NULL,
	"last_word_rank" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_word_progress" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_word_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"book_id" text NOT NULL,
	"word_rank" integer NOT NULL,
	"learned_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "user_book_progress" ADD CONSTRAINT "user_book_progress_user_id_User_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_book_progress" ADD CONSTRAINT "user_book_progress_book_id_books_bookId_fk" FOREIGN KEY ("book_id") REFERENCES "public"."books"("bookId") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_word_progress" ADD CONSTRAINT "user_word_progress_user_id_User_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_word_progress" ADD CONSTRAINT "user_word_progress_book_id_books_bookId_fk" FOREIGN KEY ("book_id") REFERENCES "public"."books"("bookId") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "user_book_progress_user_book_unique" ON "user_book_progress" USING btree ("user_id","book_id");--> statement-breakpoint
CREATE INDEX "idx_user_book_progress_user_updated" ON "user_book_progress" USING btree ("user_id","updated_at");--> statement-breakpoint
CREATE UNIQUE INDEX "user_word_progress_user_book_rank_unique" ON "user_word_progress" USING btree ("user_id","book_id","word_rank");--> statement-breakpoint
CREATE INDEX "idx_user_word_progress_user" ON "user_word_progress" USING btree ("user_id");